### ISSUE TITLE
Path.owner() is unsupported on this system

### ISSUE THREAD

**Issue by TheTyPhyter** [thetacom/hexabyte#34]
C:\\____> hexabyte .\HelloWorld.exe
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\pathlib.py:1020 in owner                                │
│                                                                                                                      │
│   1017 │   │   Return the login name of the file owner.                                                              │
│   1018 │   │   """                                                                                                   │
│   1019 │   │   try:                                                                                                  │
│ ❱ 1020 │   │   │   import pwd                                                                                        │
│   1021 │   │   │   return pwd.getpwuid(self.stat().st_uid).pw_name                                                   │
│   1022 │   │   except ImportError:                                                                                   │
│   1023 │   │   │   raise NotImplementedError("Path.owner() is unsupported on this system")                           │
│                                                                                                                      │
│ ╭─────────────── locals ───────────────╮                                                                             │
│ │ self = WindowsPath('HelloWorld.exe') │                                                                             │
│ ╰──────────────────────────────────────╯                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'pwd'

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\hexabyte\widgets\workbench.py:95 in       │
│ on_editor_selected                                                                                                   │
│                                                                                                                      │
│    92 │                                                                                                              │
│    93 │   def on_editor_selected(self, message: Editor.Selected) -> None:                                            │
│    94 │   │   """Update global state when switching editors."""                                                      │
│ ❱  95 │   │   self.active_editor = message.editor                                                                    │
│    96 │                                                                                                              │
│    97 │   def on_mount(self) -> None:                                                                                │
│    98 │   │   """Perform on_mount tasks."""                                                                          │
│                                                                                                                      │
│ ╭─────── locals ────────╮                                                                                            │
│ │ message = Selected()  │                                                                                            │
│ │    self = Workbench() │                                                                                            │
│ ╰───────────────────────╯                                                                                            │
│                                                                                                                      │
│ C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\hexabyte\widgets\workbench.py:106 in      │
│ watch_active_editor                                                                                                  │
│                                                                                                                      │
│   103 │   │   """Watch active editor to update sidebar."""                                                           │
│   104 │   │   sidebar = self.query_one("#sidebar", Sidebar)                                                          │
│   105 │   │   if self.active_editor is not None:                                                                     │
│ ❱ 106 │   │   │   sidebar.active_editor = self.active_editor                                                         │
│   107 │   │   else:                                                                                                  │
│   108 │   │   │   sidebar.active_editor = None                                                                       │
│   109                                                                                                                │
│                                                                                                                      │
│ ╭──────────── locals ─────────────╮                                                                                  │
│ │    self = Workbench()           │                                                                                  │
│ │ sidebar = Sidebar(id='sidebar') │                                                                                  │
│ ╰─────────────────────────────────╯                                                                                  │
│                                                                                                                      │
│ C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\hexabyte\widgets\sidebar.py:54 in         │
│ watch_active_editor                                                                                                  │
│                                                                                                                      │
│   51 │   def watch_active_editor(self, editor: Editor):                                                              │
│   52 │   │   """React to active api change."""                                                                       │
│   53 │   │   for panel in self.query(".panel").results(SidebarPanel):                                                │
│ ❱ 54 │   │   │   panel.editor = editor                                                                               │
│   55                                                                                                                 │
│                                                                                                                      │
│ ╭────────────────── locals ───────────────────╮                                                                      │
│ │ editor = Editor(id='primary')               │                                                                      │
│ │  panel = InfoPanel(id='sidebar-info-panel') │                                                                      │
│ │   self = Sidebar(id='sidebar')              │                                                                      │
│ ╰─────────────────────────────────────────────╯                                                                      │
│                                                                                                                      │
│ C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\hexabyte\widgets\info_panel.py:109 in     │
│ watch_editor                                                                                                         │
│                                                                                                                      │
│   106 │   │   │   filename.update(filepath.name)                                                                     │
│   107 │   │   │   path = self.query_one("#path-value", Static)                                                       │
│   108 │   │   │   path.update(f"{filepath.parent}")                                                                  │
│ ❱ 109 │   │   self.update_stats()                                                                                    │
│   110 │   │   self.update_hashes()                                                                                   │
│   111                                                                                                                │
│                                                                                                                      │
│ ╭─────────────────── locals ────────────────────╮                                                                    │
│ │ filename = Static(id='filename-value')        │                                                                    │
│ │ filepath = WindowsPath('HelloWorld.exe')      │                                                                    │
│ │     path = Static(id='path-value')            │                                                                    │
│ │     self = InfoPanel(id='sidebar-info-panel') │                                                                    │
│ ╰───────────────────────────────────────────────╯                                                                    │
│                                                                                                                      │
│ C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\site-packages\hexabyte\widgets\info_panel.py:91 in      │
│ update_stats                                                                                                         │
│                                                                                                                      │
│    88 │   │   │   kb_size = file_size // KB                                                                          │
│    89 │   │   │   size_value.update(f"{kb_size:,} KB ({file_size:,} bytes)")                                         │
│    90 │   │   owner_value = self.query_one("#owner-value", Static)                                                   │
│ ❱  91 │   │   owner_value.update(filepath.owner())                                                                   │
│    92 │   │                                                                                                          │
│    93 │   │   group_value = self.query_one("#group-value", Static)                                                   │
│    94 │   │   group_value.update(filepath.group())                                                                   │
│                                                                                                                      │
│ ╭───────────────────────────────────────────────────── locals ─────────────────────────────────────────────────────╮ │
│ │   file_size = 401920                                                                                             │ │
│ │    filepath = WindowsPath('HelloWorld.exe')                                                                      │ │
│ │     kb_size = 392                                                                                                │ │
│ │     mb_size = 0                                                                                                  │ │
│ │ owner_value = Static(id='owner-value')                                                                           │ │
│ │        self = InfoPanel(id='sidebar-info-panel')                                                                 │ │
│ │  size_value = Static(id='size-value')                                                                            │ │
│ │       stats = os.stat_result(st_mode=33279, st_ino=6755399441170242, st_dev=1078587817, st_nlink=1, st_uid=0,    │ │
│ │               st_gid=0, st_size=401920, st_atime=1710960961, st_mtime=1709313872, st_ctime=1710960920)           │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                                      │
│ C:\Users\...\AppData\Local\Programs\Python\Python311\Lib\pathlib.py:1023 in owner                                │
│                                                                                                                      │
│   1020 │   │   │   import pwd                                                                                        │
│   1021 │   │   │   return pwd.getpwuid(self.stat().st_uid).pw_name                                                   │
│   1022 │   │   except ImportError:                                                                                   │
│ ❱ 1023 │   │   │   raise NotImplementedError("Path.owner() is unsupported on this system")                           │
│   1024 │                                                                                                             │
│   1025 │   def group(self):                                                                                          │
│   1026 │   │   """                                                                                                   │
│                                                                                                                      │
│ ╭─────────────── locals ───────────────╮                                                                             │
│ │ self = WindowsPath('HelloWorld.exe') │                                                                             │
│ ╰──────────────────────────────────────╯                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
NotImplementedError: Path.owner() is unsupported on this system

**Comment by thetacom** [comment]
Windows Build 22631
